[project]
name = "mclbn256"
version = "1.3.0"
description = """\
    Python bindings for the BN254/256 pairing-friendly curve \
    supported by the MCl library.\
    """
license = {text = "MIT"}
authors = [
    {name = "Wyatt Howe"},
    {email = "Wyatt@nthparty.com"}
]
readme = "README.rst"
requires-python = ">=3.6"

[project.urls]
Repository = "https://github.com/nthparty/mclbn256"
Documentation = "https://mclbn256.readthedocs.io"

[project.optional-dependencies]
docs = [
    "toml~=0.10.2",
    "sphinx~=4.2.0",
    "sphinx-rtd-theme~=1.0.0"
]
test = [
    "pytest~=7.0",
    "pytest-cov~=3.0"
]
lint = [
    "pylint~=2.14.0"
]
coveralls = [
    "coveralls~=3.3.1"
]
publish = [
    "twine~=4.0"
]

[build-system]
requires = [
    "truckle==0.1.4",
]
build-backend = "setuptools.build_meta"

[tool.pytest.ini_options]
addopts = "--doctest-modules --ignore=docs --cov=mclbn256 --cov-report term-missing"
